window.ATL_DATA = {
  season: "2025 MLS Regular Season (Latest Completed)",
  clubName: "Atlanta United",
  record: { wins: 5, draws: 16, losses: 13 },
  stats: {
    points: 28,
    goalsFor: 33,
    goalsAgainst: 54,
    homeRecord: "4-8-5",
    awayRecord: "1-8-8",
    cleanSheets: 7,
  },
  formLastFive: ["D", "L", "L", "L", "D"],
  nextMatch: {
    opponent: "FC Cincinnati",
    dateISO: "2026-02-21T16:30:00-05:00",
    competition: "MLS",
    venue: "TQL Stadium",
    broadcast: "MLS Season Pass",
  },
  results: [
    { date: "2025-10-19", opponent: "D.C. United", venue: "Home", score: "1-1", outcome: "Draw" },
    { date: "2025-10-12", opponent: "Inter Miami CF", venue: "Away", score: "0-4", outcome: "Loss" },
    { date: "2025-10-06", opponent: "Los Angeles FC", venue: "Home", score: "0-1", outcome: "Loss" },
    { date: "2025-09-28", opponent: "New England Revolution", venue: "Away", score: "0-2", outcome: "Loss" },
    { date: "2025-09-21", opponent: "San Diego FC", venue: "Home", score: "1-1", outcome: "Draw" },
  ],
  seasonHistory: [
    { season: 2017, record: "15-9-10", points: 55, finish: "4th East", playoffs: "Lost Knockout Round" },
    { season: 2018, record: "21-7-6", points: 69, finish: "2nd East", playoffs: "MLS Cup Champions" },
    { season: 2019, record: "18-12-4", points: 58, finish: "2nd East", playoffs: "Lost Conference Final" },
    { season: 2020, record: "6-13-4", points: 22, finish: "12th East", playoffs: "Did Not Qualify" },
    { season: 2021, record: "13-9-12", points: 51, finish: "5th East", playoffs: "Lost Round One" },
    { season: 2022, record: "10-14-10", points: 40, finish: "11th East", playoffs: "Did Not Qualify" },
    { season: 2023, record: "13-9-12", points: 51, finish: "6th East", playoffs: "Lost Round One" },
    { season: 2024, record: "10-14-10", points: 40, finish: "9th East", playoffs: "Lost Conference Semifinal" },
    { season: 2025, record: "5-16-13", points: 28, finish: "14th East", playoffs: "Did Not Qualify" },
  ],
  timeline: [
    { year: "2014", text: "MLS awards Atlanta expansion franchise." },
    { year: "2017", text: "Debut MLS season and instant fan-energy identity." },
    { year: "2018", text: "MLS Cup champions at Mercedes-Benz Stadium." },
    { year: "2019", text: "U.S. Open Cup and Campeones Cup trophies." },
    { year: "Today", text: "New era focused on consistency and playoff pushes." },
  ],
};
